### ISSUE TITLE
requirements.txt missing?

### ISSUE THREAD

**Issue by srobe** [isabelshic/fluid#2]
In your README you have a section for downloading dependencies that includes:

# For Python projects
pip install -r requirements.txt

Do you have a requirements.txt file that hasn't been included? 
Or is this specific to the python packages fluid already uses? If so, I can upload that file.

**Comment by asewnath** [comment]
@isabelshic is there any python component to this project that needs to be pip installed right now? If not I'd take out instructions from `README.md` pertaining to pip installing with a `requirements.txt` file or calling python with an script.

**Comment by asewnath** [comment]
Also, just cloned, installed, and ran the react app. Nice work!

**Comment by isabelshic** [comment]
No requirements.txt - copied template from online, must've forgotten to take it out! Thanks for catching that!

**Comment by asewnath** [comment]
@isabelshic when you take out the information about python packages from `README.md`, you can go ahead and close this issue.

**Comment by isabelshic** [comment]
Got it
